// Build the crawl config used by `refresh.sh`, from the committed template.
//
// `wrangler.jsonc` ships with a placeholder database_id, and the real one lives
// in the gitignored `wrangler.local.jsonc` — which CI cannot see. So the config
// is generated: take the template, inject the id from the environment, mark the
// data bindings `remote`, and drop the crons.
//
// The crons matter. Without removing them, a `wrangler dev` session registers
// its own schedule and becomes a second collector racing the deployed one.
// This is a crawler with a borrowed IP, not a scheduler.

import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";

const collector = path.join(
	import.meta.dirname,
	"..",
	"..",
	"apps",
	"collector"
);

const databaseId = process.env.D1_DATABASE_ID;
if (!databaseId) {
	console.error("D1_DATABASE_ID is required");
	process.exit(1);
}

// JSONC: strip line comments and trailing commas before parsing. Deliberately
// simple — this reads one file we control, not arbitrary input.
const raw = readFileSync(path.join(collector, "wrangler.jsonc"), "utf-8");
const json = raw
	.replaceAll(/^\s*\/\/.*$/gmu, "")
	.replaceAll(/,(?<trailing>\s*[}\]])/gu, "$<trailing>");
const config = JSON.parse(json);

for (const binding of config.d1_databases ?? []) {
	binding.database_id = databaseId;
	binding.remote = true;
}
for (const binding of config.r2_buckets ?? []) {
	binding.remote = true;
}
delete config.triggers;
// The whole reason this config exists is to reach the endpoints the deployment
// cannot, so it always collects everything regardless of what the template says.
config.vars = { ...config.vars, COLLECTION_MODE: "all" };

const out = path.join(collector, "wrangler.localcrawl.jsonc");
writeFileSync(
	out,
	`// Generated by scripts/local-refresh/write-config.mjs — do not edit.\n${JSON.stringify(config, null, 2)}\n`
);
console.log(`wrote ${out}`);
